version: '3'

services:
  orderer:
    image: hyperledger/fabric-orderer:2.4.0
    container_name: autoauditor_orderer
    hostname: orderer.example.com
    command: orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    labels:
      autoauditor: fabric_net
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7000
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7010
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.example.com:7020
      - ORDERER_METRICS_PROVIDER=prometheus
    volumes:
        - ./network/system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./network/orderer/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - ./network/orderer/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
        - ./network/container/orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - "7000:7000"
      - "7010:7010"
      - "7020:7020"
    networks:
      - fabric_net

  peer0_org1:
    image: hyperledger/fabric-peer:2.4.0
    container_name: autoauditor_peer0_org1
    hostname: peer0.org1.example.com
    command: peer node start
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    labels:
      autoauditor: fabric_net
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=autoauditor_fabric_net
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer0.org1.example.com:8000
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8000
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:8000
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:8000
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:8010
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8010
      - CORE_OPERATIONS_LISTENADDRESS=peer0.org1.example.com:8020
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.org1.example.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ./network/org1/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
        - ./network/org1/peers/peer0.org1.example.com/tls:/etc/hyperledger/fabric/tls
        - ./network/container/org1.example.com:/var/hyperledger/production
    ports:
      - "8000:8000"
      - "8010:8010"
      - "8020:8020"
    networks:
      - fabric_net
    depends_on:
      - couchdb_org1

  peer0_org2:
    image: hyperledger/fabric-peer:2.4.0
    container_name: autoauditor_peer0_org2
    hostname: peer0.org2.example.com
    command: peer node start
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    labels:
      autoauditor: fabric_net
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=autoauditor_fabric_net
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_ADDRESS=peer0.org2.example.com:9000
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9000
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:9000
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:9000
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.example.com:9010
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9010
      - CORE_OPERATIONS_LISTENADDRESS=peer0.org2.example.com:9020
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.org2.example.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ./network/org2/peers/peer0.org2.example.com/msp:/etc/hyperledger/fabric/msp
        - ./network/org2/peers/peer0.org2.example.com/tls:/etc/hyperledger/fabric/tls
        - ./network/container/org2.example.com:/var/hyperledger/production
    ports:
      - "9000:9000"
      - "9010:9010"
      - "9020:9020"
    networks:
      - fabric_net
    depends_on:
      - couchdb_org2

  peer0_org3:
    image: hyperledger/fabric-peer:2.4.0
    container_name: autoauditor_peer0_org3
    hostname: peer0.org3.example.com
    command: peer node start
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    labels:
      autoauditor: fabric_net
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=autoauditor_fabric_net
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.org3.example.com
      - CORE_PEER_LOCALMSPID=Org3MSP
      - CORE_PEER_ADDRESS=peer0.org3.example.com:10000
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10000
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org3.example.com:10000
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org3.example.com:10000
      - CORE_PEER_CHAINCODEADDRESS=peer0.org3.example.com:10010
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10010
      - CORE_OPERATIONS_LISTENADDRESS=peer0.org3.example.com:10020
      - CORE_METRICS_PROVIDER=prometheus
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.org3.example.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    volumes:
        - /var/run/docker.sock:/host/var/run/docker.sock
        - ./network/org3/peers/peer0.org3.example.com/msp:/etc/hyperledger/fabric/msp
        - ./network/org3/peers/peer0.org3.example.com/tls:/etc/hyperledger/fabric/tls
        - ./network/container/org3.example.com:/var/hyperledger/production
    ports:
      - "10000:10000"
      - "10010:10010"
      - "10020:10020"
    networks:
      - fabric_net
    depends_on:
      - couchdb_org3

  couchdb_org1:
    image: couchdb:3.1.1
    container_name: autoauditor_couchdb_org1
    hostname: couchdb.org1.example.com
    labels:
      autoauditor: fabric_net
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "8030:5984"
    networks:
      - fabric_net

  couchdb_org2:
    image: couchdb:3.1.1
    container_name: autoauditor_couchdb_org2
    hostname: couchdb.org2.example.com
    labels:
      autoauditor: fabric_net
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "9030:5984"
    networks:
      - fabric_net

  couchdb_org3:
    image: couchdb:3.1.1
    container_name: autoauditor_couchdb_org3
    hostname: couchdb.org3.example.com
    labels:
      autoauditor: fabric_net
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "10030:5984"
    networks:
      - fabric_net

  cli:
    image: hyperledger/fabric-tools:2.4.0
    container_name: autoauditor_cli
    hostname: cli.example.com
    command: /bin/bash
    tty: true
    stdin_open: true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/autoauditor
    labels:
      autoauditor: fabric_net
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
    volumes:
        - .:/opt/gopath/src/github.com/hyperledger/fabric/autoauditor/fabric_net
        - ../fabric_net.sh:/opt/gopath/src/github.com/hyperledger/fabric/autoauditor/fabric_net.sh
    networks:
      - fabric_net
    depends_on:
      - peer0_org1
      - peer0_org2
      - peer0_org3

networks:
  fabric_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
